In [2]:
import numpy as np
import time

In [3]:
# A = [0,1,2,3,...,100000000]
# B = [0,1,2,3,...,100000000]
# C = [0,2,6,...,200000000]

In [3]:
# saf python ile kodlayalım.
baslangic = time.time()
A = list(range(10000001))
B = list(range(10000001))
C = []
for i in range(len(B)):
  toplam = A[i] + B[i]
  C.append(toplam)
bitis = time.time()
sure = bitis- baslangic
print('Saf python ile çalışma süresi:',sure)

Saf python ile çalışma süresi: 2.7547638416290283


In [8]:
veriler = ['Ahmet','Ömer','Faruk','Doğan']
#            0    ,  1    ,  2   ,   3
print(veriler[0])

for veri in veriler:
  print(veri)

print('-'*5)
for i in range(len(veriler)):
  print(veriler[i])

Ahmet
Ahmet
Ömer
Faruk
Doğan
-----
Ahmet
Ömer
Faruk
Doğan


In [4]:
# numpy ile çözümü

baslangic = time.time()
A = np.arange(10000001)
B = np.arange(10000001)
C = A + B
bitis = time.time()
sure = bitis-baslangic
print('Numpy çalışma süresi: ',sure)

Numpy çalışma süresi:  0.8103716373443604


In [7]:
numbers = [10,32,54,78,95]
arr1 = np.array(numbers)
print(arr1)
print(type(arr1))

[10 32 54 78 95]
<class 'numpy.ndarray'>


In [8]:
# arange(bitis)  arange(baslangic, bitis) arange(baslangic, bitis, miktar)
ar1 = np.arange(2,25,2)
ar1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [10]:
# linspace(baslangic, bitis, miktar) :
ar2 = np.linspace(10,34,8)
ar2

array([10.        , 13.42857143, 16.85714286, 20.28571429, 23.71428571,
       27.14285714, 30.57142857, 34.        ])

In [11]:
ar1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [13]:
a = ar1.astype(str)
a

array(['2', '4', '6', '8', '10', '12', '14', '16', '18', '20', '22', '24'],
      dtype='<U21')

In [15]:
# 1 lerden oluşan diziler
# ones(adet)
birler = np.ones(6).astype(int)
birler

array([1, 1, 1, 1, 1, 1])

In [18]:
#zeros(adet) sıfırlardan oluşan diziler oluşturmak için kullanılır.
sifirlar = np.zeros(25).astype(int)
sifirlar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [19]:
# repeat(sayı, adet) :
ar3 = np.repeat(25,6)
ar3

array([25, 25, 25, 25, 25, 25])

In [26]:
ar4 = np.repeat([10,20,30],3)
ar4

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [27]:
np.tile([10,20,30],3)

array([10, 20, 30, 10, 20, 30, 10, 20, 30])

In [31]:
# Random sayılar
a = np.random.randn(25)
a


array([-1.13593058,  0.71628751, -0.18767646, -1.33276578,  0.76926612,
        0.73813042, -0.52988389,  0.24233336, -1.68707279,  1.43137921,
       -1.17919985, -0.89573898,  1.68775104,  0.31360472, -0.0842096 ,
        0.95375805, -0.96241516,  1.52349882,  0.27807657,  0.46193219,
        1.8601452 ,  0.22887997, -0.74513741,  0.11343442, -2.16311616])

In [35]:
b = np.random.randint(123,654,150)

In [36]:
b

array([437, 248, 322, 465, 370, 568, 564, 133, 285, 543, 469, 174, 188,
       459, 623, 228, 345, 553, 368, 230, 550, 127, 270, 175, 188, 499,
       611, 584, 394, 287, 473, 207, 617, 596, 474, 323, 215, 141, 138,
       235, 140, 321, 549, 169, 496, 357, 238, 157, 577, 541, 584, 530,
       645, 463, 208, 220, 267, 530, 204, 342, 572, 360, 500, 487, 520,
       522, 136, 619, 212, 385, 414, 645, 412, 291, 148, 209, 152, 448,
       612, 311, 220, 494, 580, 328, 180, 648, 384, 416, 569, 140, 537,
       372, 495, 393, 537, 270, 461, 486, 198, 295, 471, 330, 372, 337,
       507, 238, 147, 317, 652, 460, 319, 448, 311, 328, 441, 451, 608,
       646, 568, 356, 331, 642, 640, 338, 218, 418, 410, 328, 579, 200,
       496, 247, 244, 421, 557, 423, 502, 465, 239, 570, 486, 381, 193,
       400, 534, 595, 613, 194, 635, 454])

In [37]:
b

array([437, 248, 322, 465, 370, 568, 564, 133, 285, 543, 469, 174, 188,
       459, 623, 228, 345, 553, 368, 230, 550, 127, 270, 175, 188, 499,
       611, 584, 394, 287, 473, 207, 617, 596, 474, 323, 215, 141, 138,
       235, 140, 321, 549, 169, 496, 357, 238, 157, 577, 541, 584, 530,
       645, 463, 208, 220, 267, 530, 204, 342, 572, 360, 500, 487, 520,
       522, 136, 619, 212, 385, 414, 645, 412, 291, 148, 209, 152, 448,
       612, 311, 220, 494, 580, 328, 180, 648, 384, 416, 569, 140, 537,
       372, 495, 393, 537, 270, 461, 486, 198, 295, 471, 330, 372, 337,
       507, 238, 147, 317, 652, 460, 319, 448, 311, 328, 441, 451, 608,
       646, 568, 356, 331, 642, 640, 338, 218, 418, 410, 328, 579, 200,
       496, 247, 244, 421, 557, 423, 502, 465, 239, 570, 486, 381, 193,
       400, 534, 595, 613, 194, 635, 454])

In [38]:
# elemanlarının toplamı
sum(b)

np.int64(59232)

In [40]:
toplam = np.sum(b)
print(toplam)

59232


In [41]:
print(b.sum())

59232


In [42]:
# ortalama hesaplam :
ortalama = np.mean(b)
print(ortalama)

394.88


In [43]:
print(b.mean())

394.88


In [44]:
# standart sapma
std_sapma = np.std(b)
print(std_sapma)

154.05098376836156


In [45]:
print(b.std())

154.05098376836156


In [46]:
A = np.array([1,2,3])
B = np.array([10,45,78])

In [47]:
C = A + B
print(C)

[11 47 81]


In [48]:
A = np.random.randint(0,1000,121)
A

array([724, 447, 283, 399,  93, 940,  67, 322, 666,  81, 531, 344, 848,
       910, 129, 133, 510, 601, 605, 546, 881, 235, 750, 798, 280, 278,
       121, 676, 175, 426, 122,   1, 656, 485, 839, 478, 699, 964, 849,
       867, 177, 465, 295, 375, 761, 805, 818,  24, 843, 196, 423, 923,
       826, 979, 848, 838,  23, 871, 329, 616, 453, 890, 736, 635, 775,
       179, 853, 928, 559, 178, 979, 615, 253, 987, 635, 798, 429, 228,
       225, 364, 148, 910, 710, 155, 859, 360, 357, 524, 758, 586, 229,
       854, 281, 318,  90, 972,  64, 627, 452, 448, 899, 822, 112, 871,
       182, 888, 327, 481,  96, 808, 966, 397,  63,  97, 588, 438, 772,
        19, 198, 154,  19])

In [50]:
matris = A.reshape(11,11)
matris

array([[724, 447, 283, 399,  93, 940,  67, 322, 666,  81, 531],
       [344, 848, 910, 129, 133, 510, 601, 605, 546, 881, 235],
       [750, 798, 280, 278, 121, 676, 175, 426, 122,   1, 656],
       [485, 839, 478, 699, 964, 849, 867, 177, 465, 295, 375],
       [761, 805, 818,  24, 843, 196, 423, 923, 826, 979, 848],
       [838,  23, 871, 329, 616, 453, 890, 736, 635, 775, 179],
       [853, 928, 559, 178, 979, 615, 253, 987, 635, 798, 429],
       [228, 225, 364, 148, 910, 710, 155, 859, 360, 357, 524],
       [758, 586, 229, 854, 281, 318,  90, 972,  64, 627, 452],
       [448, 899, 822, 112, 871, 182, 888, 327, 481,  96, 808],
       [966, 397,  63,  97, 588, 438, 772,  19, 198, 154,  19]])

In [53]:
A = np.array([1,2,3])
B = np.array([10,45,78,85])
C = A + B
print(C)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 